export interface IParticipante {
    id: number;
    name: string;
    imgUrl: string;
    universo: number;
    planeta: string;
    poderPelea: string;
}

export const participantes: IParticipante[] = [
    {
        id: 1,
        name: 'Son Goku',
        imgUrl: '../../assets/img/participantes/Son_Goku.png',
        universo: 7,
        planeta: 'Tierra',
        poderPelea: '4.944.000 B max',
    },
    {
        id: 2,
        name: 'Son Gohan',
        imgUrl: '../../assets/img/participantes/Son_Gohan.png',
        universo: 7,
        planeta: 'Tierra',
        poderPelea: '55 B max',
    },
    {
        id: 3,
        name: 'Son Goten',
        imgUrl: '../../assets/img/participantes/Son_Goten.png',
        universo: 7,
        planeta: 'Tierra',
        poderPelea: '570 M max',
    },
    {
        id: 4,
        name: 'Trunks',
        imgUrl: '../../assets/img/participantes/Trunks.png',
        universo: 7,
        planeta: 'Tierra',
        poderPelea: '590 M max',
    },
    {
        id: 5,
        name: 'Videl',
        imgUrl: '../../assets/img/participantes/Videl.png',
        universo: 7,
        planeta: 'Tierra',
        poderPelea: '70 max',
    },
    {
        id: 6,
        name: 'Mr. Satan',
        imgUrl: '../../assets/img/participantes/Mr_Satan.png',
        universo: 7,
        planeta: 'Tierra',
        poderPelea: '137 max',
    },
    {
        id: 7,
        name: 'Vegeta',
        imgUrl: '../../assets/img/participantes/Vegeta.png',
        universo: 7,
        planeta: 'Vegeta',
        poderPelea: '480.000 B max',
    },
    {
        id: 8,
        name: 'Ten Shin Han',
        imgUrl: '../../assets/img/participantes/Tenshinhan.png',
        universo: 7,
        planeta: 'Namekusei',
        poderPelea: '800.000 max',
    },
    {
        id: 9,
        name: 'Yamcha',
        imgUrl: '../../assets/img/participantes/Yamcha.png',
        universo: 7,
        planeta: 'Tierra',
        poderPelea: '600.000 max',
    },
    {
        id: 10,
        name: 'Krillin',
        imgUrl: '../../assets/img/participantes/Krilin.png',
        universo: 7,
        planeta: 'Tierra',
        poderPelea: '600,000 max',
    },
    {
        id: 11,
        name: 'Roshi',
        imgUrl: '../../assets/img/participantes/Roshi.png',
        universo: 7,
        planeta: 'Tierra',
        poderPelea: 'Desconocido',
    },
    {
        id: 12,
        name: 'Chaoz',
        imgUrl: '../../assets/img/participantes/Chaoz.png',
        universo: 7,
        planeta: 'Tierra',
        poderPelea: '25.000 max',
    },
    {
        id: 13,
        name: 'Cell',
        imgUrl: '../../assets/img/participantes/Cell.png',
        universo: 7,
        planeta: 'Laboratorio de Gero, Tierra',
        poderPelea: '3 B max',
    },    
    {
        id: 14,
        name: 'Tao Pai Pai',
        imgUrl: '../../assets/img/participantes/Tao_Pai_Pai.png',
        universo: 7,
        planeta: 'Tierra',
        poderPelea: '210 max',
    },
    {
        id: 15,
        name: 'Piccolo',
        imgUrl: '../../assets/img/participantes/Piccolo.png',
        universo: 7,
        planeta: 'Namekusei',
        poderPelea: '3 B max',
    },
    {
        id: 16,
        name: 'Androide N18',
        imgUrl: '../../assets/img/participantes/Androide_18.png',
        universo: 7,
        planeta: 'Tierra',
        poderPelea: '245 M max',
    },
    {
        id: 17,
        name: 'Paikuhan (Pikkon)',
        imgUrl: '../../assets/img/participantes/Paikuhan.png',
        universo: 7,
        planeta: 'Galaxias del Oeste',
        poderPelea: '400 M max',
    },
    {
        id: 18,
        name: 'Dabura (Darbra)',
        imgUrl: '../../assets/img/participantes/Dabura.png',
        universo: 7,
        planeta: 'Reino Demonio',
        poderPelea: '350 M max',
    },
    {
        id: 19,
        name: 'Freezer',
        imgUrl: '../../assets/img/participantes/Freezer.png',
        universo: 7,
        planeta: 'Desconocido',
        poderPelea: '480.000 B max',
    },
    {
        id: 20,
        name: 'Jiren',
        imgUrl: '../../assets/img/participantes/Jiren.png',
        universo: 11,
        planeta: 'Desconocido',
        poderPelea: '1.750.000 B max',
    },
];